---
title: "R-Adelaide Workshop"
author: 'University of Adelaide, Bioinformatics Hub'
date: "July 20-22, 2016"
output: html_document
---

# Computer Setup

## R

Please ensure you have the latest version of `R`.
The current version (`R-3.3.1`) is available at http://cran.ms.unimelb.edu.au/
`R` should be installed on your computer before installing `R Studio`


## R Studio
Please ensure you have the latest version of `R Studio`
The current version(`RStudio 0.99.902`) is available at [https://www.rstudio.com/](https://www.rstudio.com/products/rstudio/download/)

R Studio will usually automatically detect your most recent version of R and will use this by default.

## R Packages
To install all required packages, please execute the following command in R.
You can copy & paste straight from this page into R.

```{r, eval=FALSE}
source("http://uofabioinformaticshub.github.io/RAdelaide-July-2016/rAdelaideInstaller.R")
```

If you have problems with  installation related to the package `dplyr`, see the notes at the bottom of the page.
Otherwise, please come to the Bioinformatics Hub, Level 4, Santos Petroleum Engineering Building between 4pm and 6pm on Tuesday 19th July.

## Connecting to Nectar

In order to take part in the "R-Studio in the Cloud" session, attendees will need an active NeCTAR project. Here is a [link to the user guide](https://support.nectar.org.au/support/solutions/articles/6000055377-getting-an-account) for accessing the NeCTAR dashboard using your AAF (institutional) login.

- Go the [NeCTAR dashboard page](https://dashboard.rc.nectar.org.au) and confirm that you can log in using your AAF credentials. 
When you do this for the first time, you will activate a new trial project allocation.
If you do not have an AAF login, please advise Steve during one of the breaks before the Thursday afternoon session

- If you have previously logged onto the dashboard confirm that your trial project is still active, and if not request an extension for this course. 
To request an extension, go to the Allocations tab of the dashboard and fill in a New Allocation request.
Explain that you will be doing this course and give the date on which you will be doing the course.

- If your laptop is running Windows, you will need an SSH client. 
Go to the [PuTTY download page](http://www.chiark.greenend.org.uk/~sgtatham/putty/download)
Download and run  `putty-0.67-installer.msi`.
If you don't have administrative access to your computer, just download `putty.exe` and this will be sufficient.


## Seting Up Your Internet Browser

Although not required, installing a plugin/addon for your browser which can view Markdown may be beneficial.
Suitable viewers are [Markdown Viewer For Chrome](https://chrome.google.com/webstore/detail/markdown-viewer/ehnambpmkdhopilaccgfmojilolcglhn)
or [Markdown Viewer For Firefox](https://addons.mozilla.org/en-US/firefox/addon/markdown-viewer/)


## Problems with installation of R packages

If you receive an error message when running the above code, Steve will be available in the Bioinformatics Hub (Level 4, Santos Petroleum Engineering Building) from 4pm to 6pm on Tuesday 19th July.
If your error message was specifically regarding the package `dplyr`please keep reading.

### The package `dplyr`

Installing the package `dplyr` can be problematic on University laptops running Windows.
If you are having problems, follow these steps:

1. Create a new folder `C:\R`  
2. Create a new `Environment Variable` (see below) called `R_LIBS_USER` and give it the value `C:\R`.
The steps below can guide you through this.

#### Windows 10 and Windows 8

1. In Search, search for and then select: `System (Control Panel)`
2. Click the `Advanced` system settings link.
3. Click `Environment Variables`. 
4. In the User Variables Section, click `New...`
5. Name the New Variable `R_LIBS_USER` and specify the value `C:\R`

#### Windows 7

1. From the desktop, right click the Computer icon.
2. Choose Properties from the context menu.
3. Click the `Advanced` system settings link.
4. Click `Environment Variables`. 
5. In the User Variables Section, click `New...`
6. Name the New Variable `R_LIBS_USER` and specify the value `C:\R`

